ecommerce/apps/charts/urls.py
from django.urls import path

from . import views

app_name = "charts"

urlpatterns = [
    path("", views.home, name="dashboard"),
]

ecommerce/apps/session/urls.py
from django.urls import path
from . import views

app_name = 'session'

urlpatterns = [
    path('', views.basket_home, name="basket"),
    path('add/', views.add, name="add"),
    path('update/', views.update, name="update"),
    path('delete', views.delete, name="delete"),

]

ecommerce/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('api/', include('ecommerce.apps.offert_api.urls', namespace='blog_api')),
    path("dashboard/", include("ecommerce.apps.charts.urls", namespace="charts")),
    path("basket/", include("ecommerce.apps.session.urls", namespace="session")),
    path("", include("ecommerce.apps.offert.urls", namespace="offert")),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load custom_template_tags %}
<html>

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="icon" type="image/png" href="https://image.flaticon.com/icons/png/512/911/911412.png" />
	<title>{% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
		integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous">
	</script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
		integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous">
	</script>
	<!--Chart.js-->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.1/chart.min.js"></script>
	<!--jQuery-->
	<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
	<!-- Google Icons -->
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static "base/css/base.css" %}">
	<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% endblock %}">
</head>

<body>
	<nav class="p-1">
		<div class="container fluid">
			<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start me-lg-auto mt-2">
				<a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none me-lg-auto">
					<span class="fs35">H</span>
					<svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-cpu"
						viewBox="0 0 16 16">
						<path
							d="M5 0a.5.5 0 0 1 .5.5V2h1V.5a.5.5 0 0 1 1 0V2h1V.5a.5.5 0 0 1 1 0V2h1V.5a.5.5 0 0 1 1 0V2A2.5 2.5 0 0 1 14 4.5h1.5a.5.5 0 0 1 0 1H14v1h1.5a.5.5 0 0 1 0 1H14v1h1.5a.5.5 0 0 1 0 1H14v1h1.5a.5.5 0 0 1 0 1H14a2.5 2.5 0 0 1-2.5 2.5v1.5a.5.5 0 0 1-1 0V14h-1v1.5a.5.5 0 0 1-1 0V14h-1v1.5a.5.5 0 0 1-1 0V14h-1v1.5a.5.5 0 0 1-1 0V14A2.5 2.5 0 0 1 2 11.5H.5a.5.5 0 0 1 0-1H2v-1H.5a.5.5 0 0 1 0-1H2v-1H.5a.5.5 0 0 1 0-1H2v-1H.5a.5.5 0 0 1 0-1H2A2.5 2.5 0 0 1 4.5 2V.5A.5.5 0 0 1 5 0zm-.5 3A1.5 1.5 0 0 0 3 4.5v7A1.5 1.5 0 0 0 4.5 13h7a1.5 1.5 0 0 0 1.5-1.5v-7A1.5 1.5 0 0 0 11.5 3h-7zM5 6.5A1.5 1.5 0 0 1 6.5 5h3A1.5 1.5 0 0 1 11 6.5v3A1.5 1.5 0 0 1 9.5 11h-3A1.5 1.5 0 0 1 5 9.5v-3zM6.5 6a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z" />
					</svg>
					<span class="fs35">me</span>
				</a>
				<form class="col-12 col-lg-6 mb-3 mb-lg-0 me-lg-3 p-2">
					<div class="input-group">
						<input type="text" class="form-control" placeholder="Search..." aria-label="Search"
							id="button-left">
						<button type="submit" class="d-flex flex-row align-items-center btn btn-primary submit-button"
							id="button-right">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
								class="bi bi-search" viewBox="0 0 16 16">
								<path
									d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
								</svg>
							<span class="ps-2">Search</span>
						</button>
					</div>
				</form>
				<div class="d-flex flex-row">
					<a href="#" class="nav-link nav-main link-dark">
						<div class="d-flex flex-column  align-items-center">
							<svg xmlns="http://www.w3.org/2000/svg cl" height="30" width="30" viewBox="0 0 24 24"
								fill="#000000">
								<path d="M0 0h24v24H0V0z" fill="none" />
								<path
									d="M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z" />
								</svg>
							<span class="fw500">Notifications</span>
						</div>
					</a>
					<a href="#" class="nav-link nav-main link-dark">
						<div class="d-flex flex-column  align-items-center">
							<svg xmlns="http://www.w3.org/2000/svg" height="30" viewBox="0 0 24 24" width="30"
								fill="#000000">
								<path d="M0 0h24v24H0V0z" fill="none" />
								<path
									d="M12 6c1.1 0 2 .9 2 2s-.9 2-2 2-2-.9-2-2 .9-2 2-2m0 10c2.7 0 5.8 1.29 6 2H6c.23-.72 3.31-2 6-2m0-12C9.79 4 8 5.79 8 8s1.79 4 4 4 4-1.79 4-4-1.79-4-4-4zm0 10c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z" />
								</svg>
							<span class="fw500">Account</span>
						</div>
					</a>
					{% if user.is_superuser %}
					<a href="{% url 'charts:dashboard' %}" class="nav-link nav-main link-dark">
						<div class="d-flex flex-column  align-items-center">
							<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-speedometer2" viewBox="0 0 16 16">
							<path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
							<path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
							</svg>
							<span class="fw500">Dashboard</span>
						</div>
					</a>
					{% endif %}
					<a href="{% url 'session:basket' %}" class="nav-link nav-main link-dark">
						<div class="d-flex flex-column  align-items-center position-relative">
							<svg xmlns="http://www.w3.org/2000/svg" height="30" viewBox="0 0 24 24" width="30"
								fill="#000000">
								<path d="M0 0h24v24H0V0z" fill="none" />
								<path
									d="M22 9h-4.79l-4.38-6.56c-.19-.28-.51-.42-.83-.42s-.64.14-.83.43L6.79 9H2c-.55 0-1 .45-1 1 0 .09.01.18.04.27l2.54 9.27c.23.84 1 1.46 1.92 1.46h13c.92 0 1.69-.62 1.93-1.46l2.54-9.27L23 10c0-.55-.45-1-1-1zM12 4.8L14.8 9H9.2L12 4.8zM18.5 19l-12.99.01L3.31 11H20.7l-2.2 8zM12 13c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z" />
								</svg>
								<span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" id="total-items">
									{{session.total_items_number}}
									<span class="visually-hidden">unread messages</span>
								</span>
							<span class="fw500">Basket</span>
						</div>
					</a>
				</div>
			</div>
		</div>
	</nav>
	<main class="pt-1">
		<div class="container pt-3 ps-0 pe-0">
			{% if messages %}
				{% for message in messages %}
				<div class="alert alert-{{ message.tags }}">
					{{ message }}
				</div>
				{% endfor %}
			{% endif %}
		</div>
		<div id="content">{% block content %} {% endblock %}</div>
	</main>
	<footer class="container py-5 footer">
		<div class="container fluid">
			<footer class="py-3 my-4">
				<ul class="nav justify-content-center border-bottom pb-3 mb-3">
					<li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
					<li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
					<li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
					<li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
					<li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
				</ul>
				<p class="text-center text-muted">© 2021 Company, Inc</p>
			</footer>
		</div>
	</footer>
	<script type="text/javascript" src="{% block javascript %}{% endblock %}"></script>
</body>

</html>