ecommerce/apps/offert/urls.py
from django.urls import path

from . import views

app_name = "offert"

urlpatterns = [
    path("", views.home, name="offert"),
    path("<slug:slug>/", views.subcategory, name="subcategory"),
    path("<slug:slug>/products/", views.get_category_products, name="products"),
    path("<slug:slug>/products/<slug:slug_product>/",
         views.indyvidual_product, name="products_indyvidual"),
]

ecommerce/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('api/', include('ecommerce.apps.offert_api.urls', namespace='blog_api')),
    path("dashboard/", include("ecommerce.apps.charts.urls", namespace="charts")),
    path("basket/", include("ecommerce.apps.session.urls", namespace="session")),
    path("", include("ecommerce.apps.offert.urls", namespace="offert")),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

ecommerce/apps/offert/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey
from django.dispatch import receiver
from ecommerce.settings import PRODUCT_DEFAULT_IMAGE_NAME

User = get_user_model()


class Category(MPTTModel):
    """
    MPTT Model allow us simple access to hierarchical data
    """

    name = models.CharField(verbose_name=_(
        "Group Name"), max_length=255, unique=True)
    photo = models.ImageField(upload_to="category/",
                              default="category/default_photo.png")
    slug = models.SlugField(verbose_name=_(
        "Group Slug"), max_length=255, unique=True)
    parent = TreeForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="children"
    )

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.name


class Feature(models.Model):
    """
    Contain certain product specification with define value
    """

    name = models.CharField(verbose_name=_(
        "Feature Name"), max_length=255, unique=True)
    category = models.ManyToManyField(
        Category, related_name="feature_categories", through="FeatureCategory"
    )

    def __str__(self):
        return f"{self.name}"


class FeatureCategory(models.Model):
    """
    Connection between Feature and Category
    """

    feature = models.ForeignKey(Feature, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        unique_together = ["feature", "category"]

    def __str__(self):
        return f"{self.feature} : {self.category}"


class Product(models.Model):
    """
    Contain product items
    """

    name = models.CharField(verbose_name=_(
        "Product Name"), max_length=255, unique=True)
    slug = models.SlugField(verbose_name=_(
        "Slug"), max_length=255, unique=True)
    category = TreeForeignKey(Category, on_delete=models.PROTECT)
    features = models.ManyToManyField(
        Feature, related_name="features", through="ProductFeature"
    )
    description = models.TextField(
        verbose_name=_("Product Description"), blank=True)
    added_by = models.ForeignKey(
        User, related_name="product_creator", on_delete=models.CASCADE
    )
    added_at = models.DateTimeField(auto_now_add=True, editable=False)
    last_modification = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)
    quantity = models.DecimalField(max_digits=5, decimal_places=0)
    calatog_number = models.DecimalField(max_digits=10, decimal_places=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProductRate(models.Model):
    """
    All users opinion about product
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    value = models.DecimalField(max_digits=2, decimal_places=1)


class ProductFeature(models.Model):
    """
    ManytoMany Relationship connector
    """

    product = models.ForeignKey(
        Product, related_name="product_product", on_delete=models.CASCADE
    )
    feature = models.ForeignKey(
        Feature, related_name="product_feature", on_delete=models.CASCADE
    )
    value = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        verbose_name=_("Feature Value"),
        help_text="max 6 digit, 2 decimal place",
    )

    class Meta:
        unique_together = ["product", "feature"]

    def __str__(self):
        return f"{self.product} : {self.feature}"


class Images(models.Model):
    """
    Product images details
    """

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="product_image"
    )
    default = models.BooleanField(default=False)
    image = models.ImageField(
        upload_to="images/", verbose_name=_("image"), default=PRODUCT_DEFAULT_IMAGE_NAME
    )

    class Meta:
        verbose_name = _("Image")
        verbose_name_plural = _("Images")


class Price(models.Model):
    """
    Product price details
    """

    product = models.OneToOneField(Product, on_delete=models.CASCADE)
    regular = models.DecimalField(
        max_digits=6, decimal_places=2, verbose_name="Normal Price"
    )
    day_product_price = models.DecimalField(
        max_digits=6, decimal_places=2, verbose_name="Day Product Price"
    )
    day_product = models.BooleanField(default=False)
    in_sale_price = models.DecimalField(
        max_digits=6, decimal_places=2, verbose_name="Sale Price"
    )
    in_sale = models.BooleanField(default=False)

    # Comparison is time consuming and shloud be replaced by signals utility
    def save(self, *args, **kwargs):
        if self.pk is not None:
            orig = Price.objects.get(pk=self.pk)
            if orig.day_product != self.day_product:
                Price.objects.exclude(id=self.pk).update(day_product=False)
            if orig.in_sale != self.in_sale and self.day_product:
                self.day_product = False
        if self.day_product:
            self.in_sale = False
        super().save(*args, **kwargs)

ecommerce/apps/offert/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from .models import Category, Price, Product, Images
from ecommerce.apps.offert.offert import Offert
import numpy as np
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def home(request):
    home = Offert()
    category_list, category_len, carousel_qty, category = home.get_category_list()
    sale_list, sale_len, images, percentage_sale, sale = home.get_sale_list()
    descendent_count = [des.get_descendant_count() for des in category]

    context = {
        'price_day': home.price_day,
        'percentage': home.day_product_percentage(),
        'available_qty': home.available_quantity(),
        'category_list': category_list,
        'carousel_qty': range(carousel_qty),
        'category_len': category_len,
        'day_product': home.day_product,
        'day_product_image': home.day_product_image,
        'sale_list': sale_list,
        'sale_len': sale_len,
        'sale_qty': range(sale_len),
        'images': images,
        'percentage_sale': dict(zip(sale, percentage_sale)),
        'descendent_count': dict(zip(category, descendent_count)),
    }
    return render(request, "offert/index.html", context)


def subcategory(request, slug):
    category = Category.objects.filter(parent_id__slug=slug)
    descendent_count = [des.get_descendant_count() for des in category]

    try:
        # Get one category to define ancestors
        category_anc = category.first()
        ancestors = [m for m in category_anc.get_ancestors(
            ascending=False, include_self=False)]
    except:
        raise Http404

    title = slug.capitalize()

    context = {
        'category': category,
        'title': title,
        'ancestors': ancestors,
        'descendent_count': dict(zip(category, descendent_count)),
    }
    return render(request, "offert/subcategory.html", context)


def get_category_products(request, slug):
    product = Offert(slug=slug)
    category, products, ancestors, images, percentage_pr = product.get_product_list()
    # items_per_page = 4
    # page = request.GET.get('page', 1)

    # paginator_pr = Paginator(products, items_per_page)
    # paginator_im = Paginator(images, items_per_page)
    # paginator_per = Paginator(percentage_pr, items_per_page)

    # try:
    #     products = paginator_pr.page(page)
    #     images = paginator_im.page(page)
    #     percentage_pr = paginator_per.page(page)
    # except PageNotAnInteger:
    #     products = paginator_pr.page(1)
    #     images = paginator_im.page(1)
    #     percentage_pr = paginator_per.page(1)
    # except EmptyPage:
    #     products = paginator_pr.page(paginator_pr.num_pages)
    #     images = paginator_im.page(paginator_im.num_pages)
    #     percentage_pr = paginator_per.page(paginator_per.num_pages)

    context = {
        'category': category,
        'products': products,
        'ancestors': ancestors,
        'images': images,
        'percentage_pr':  dict(zip(products, percentage_pr)),
    }

    return render(request, "offert/products.html", context)


def indyvidual_product(request, slug, slug_product):
    product = Offert(slug=slug, slug_product=slug_product)
    (product, images, product_rate, product_rate_len, product_features,
     ancestors, stars, half_star, empty_stars, feature_value_dict,
     feature_len) = product.product_indyvidual()

    images_len = range(len(images))

    context = {
        'product': product,
        'images': images,
        'product_rate': product_rate,
        'product_rate_len': product_rate_len,
        'product_features': product_features,
        'ancestors': ancestors,
        'images_len': images_len,
        'stars': range(stars),
        'half_star': half_star,
        'empty_stars': range(empty_stars),
        'feature_value_dict': feature_value_dict,
        'feature_len': feature_len,
    }

    return render(request, "offert/product_indyvidual.html", context)

templates/offert/_carousel_category.html
<div id="myCarousel" class="carousel carousel-dark slide" data-bs-ride="carousel">
    {% if user.is_superuser %}
    <div class="d-flex flex-row justify-content-center pb-4" style="background-color: #f5f5f5";>
        <h1 class="mt-3 text-center">Categories</h1>
    </div>
    {% endif %}
    <div class="carousel-indicators">
    {% for c in carousel_qty %}
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="{{c}}" {% if c == 0 %} class="active" {% endif %}
            aria-label="Slide {{c}}"></button>
    {% endfor %}
    </div>
    <div class="carousel-inner">
        {% for c in carousel_qty %}
        {% if c == 0 %}<div class="carousel-item active main">{% else %}<div class="carousel-item main">{% endif %}
            <div class="container">
                <div class="carousel-caption main">
                    <div class="d-flex flex-row flex-wrap justify-content-between">
                        {% for category in category_list|get_position_upper:c %}
                            <div class="d-fled flex-row">
                                <img src="{{category.photo.url}}" width="100" height="100"
                                    class="round-border" alt="No data">
                                </span>
                                <div>
                                    <span class="fs18 fw500">{{category.name}}</span>
                                </div>
                                <div class="pt-2">
                                    <button type="button" class="btn btn-secondary btn-sm">
                                        {% if descendent_count|put_variable:category != 0 %}
                                        <a href="{% url 'offert:subcategory' category.slug %}" class="my-link link-light">View more</a>
                                        {% else %}
                                        <a href="{% url 'offert:products' category.slug %}" class="my-link link-light">View more</a>
                                        {% endif %}
                                    </button>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                    <div class="d-flex flex-row flex-wrap pt-5 justify-content-between">
                        {% for category in category_list|get_position_bottom:c %}
                            <div class="d-fled flex-row">
                                <img src="{{category.photo.url}}" width="100" height="100"class="round-border" alt="No data">
                                <div>
                                    <span class="fs18 fw500">{{category.name}}</span>
                                </div>
                                <div class="pt-2">
                                    <button type="button" class="btn btn-secondary btn-sm">
                                        {% if descendent_count|put_variable:category != 0 %}
                                        <a href="{% url 'offert:subcategory' category.slug %}" class="my-link link-light">View more</a>
                                        {% else %}
                                        <a href="{% url 'offert:products' category.slug %}" class="my-link link-light">View more</a>
                                        {% endif %}
                                    </button>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% if category_list|length > 2 %}
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
    {% endif %}
</div>

templates/offert/_day_product.html
<a href="{% url 'offert:products_indyvidual' day_product.category.slug day_product.slug %}" class="text-decoration-none text-dark">
	<div class="d-flex flex-column">
		<div class="d-flex flex-row">
			<img src="{{day_product_image.image.url}}" width="150" height="150" class=""
				alt="No data">
			<div class="card text-center ms-auto align-self-center">
				<div class="card-header price-header">
					<span class="text-white">-{{percentage}}%</span>
				</div>
				<div class="card-body align-items-center border-start border-end border-bottom rounded-bottom">
					<div class="d-flex flex-column">
						<span>{{day_product.name}}</span>
						<span class="text-muted text-decoration-line-through fs12">{{price_day.regular}}$</span>
						<span>{{price_day.day_product_price}}$</span>
					</div>
				</div>
			</div>
		</div>
		<div class="progress mt-2">
			<div class="progress-bar bg-success" role="progressbar" style="width: {{available_qty}}%" aria-valuenow="25" aria-valuemin="0"
				aria-valuemax="100">{{available_qty}}%</div>
		</div>
	</div>
</a>

templates/offert/products.html
{% extends "base.html" %}
{% load static %}
{% load custom_template_tags %}
{% block title %}{{ancestors|last}}{% endblock %}
{% block stylesheet %}{% static "offert/css/offert_products.css" %}{% endblock %}
{% block content %}
<div class="container pt-5">
    <div class="row">
        <div class="col-3 col-xs-6 col-sm-3 col-md-3">
            <div class="card">
                <div class="card-header text-center header-filter border">
                    <span class="fs-5">Price</span>
                </div>
                <div class="card-body border-start border-end border-bottom text-center">
                    <label for="customRange1" class="form-label fs-6">Min</label>
                    <input type="range" class="form-range" min="0" max="5" step="0.5" id="customRange1">
                    <label for="customRange2" class="form-label fs-6">Max</label>
                    <input type="range" class="form-range" min="0" max="5" step="0.5" id="customRange2">
                    <span class="fs-6">Price_min - Price max $</span>
                </div>
            </div>
            <div class="d-grid gap-2">
                <a href="#" class="btn btn-primary mt-3">
                    <span class="fs-4">Filter</span>
                </a> 
            </div>
        </div>
        <div class="col-9 col-xs-6 col-sm-9 col-md-9">
            <div class="d-flex flex-row align-items-center">
                {% for an in ancestors %}
                {% if an == ancestors|last %}
                    <span class="text-decoration-none navigator-text fw-bold">{{an.name}}</span> 
                {% else %}
                    <a href="{% url 'offert:subcategory' an.slug %}" class="text-decoration-none text-dark navigator-text fw-bold">{{an.name}}</a>
                {% endif %}
                {% if an != ancestors|last %}
                    <svg xmlns="http://www.w3.org/2000/svg" class="ms-2 me-2" width="30" height="30" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                    </svg>
                {% endif %}
                {% endfor %}
            </div>
            <hr class="ms-0 me-0 mt-3 mb-3">
            <div>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <hr class="ms-0 me-0 mt-3 mb-3">
            <div class="d-flex flex-row">
                <div class="mb-5 d-flex align-items-center">
                    <span class="fs-6">Sorted by:</span>
                    <select class="d-flex ms-3  justify-content-center align-items-center custom-select fs-6 p-2">
                        <option selected value="1">Price</option>
                        <option value="2">Date Creation</option>
                        <option value="3">Last modification</option>
                        <option value="4">Opinions</option>
                    </select>
                </div>
                <div class="mb-5 ms-3 d-flex align-items-center">
                    <span class="fs-6">Items per page:</span>
                    <select class="d-flex  justify-content-center align-items-center ms-3 custom-select fs-6 p-2">
                        <option selected value="1">4</option>
                        <option value="2">8</option>
                        <option value="3">12</option>
                        <option value="4">16</option>
                    </select>
                </div>
                <div class="d-flex ms-auto mb-5">
                    <button type="button" class="ms-3 btn btn-primary">Apply</button>
                </div>
            </div>
            <div class="row">
                {% for pr in products %}
                <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3">
                    <div class="card mb-5 subcategory-product-card">
                        {% if pr.available %}
                            <div class="card-header header-succ text-center">
                                <span class="text-white">Product available</span>
                            </div>
                        {% else %}
                            <div class="card-header header-warn text-center">
                                <span class="text-white">Product unavailable</span>
                            </div>
                        {% endif %}
                        <a href="{% url 'offert:products_indyvidual' pr.category.slug pr.slug %}" class="text-decoration-none text-dark">
                            <div class="card-body border-start border-end">
                                <div class="row">
                                    <div class="col-7 p-1">
                                        <div class="card">
                                            {% for i in images %}
                                                {% if i.product.pk == pr.pk %}
                                                    <img src="{{i.image.url}}" class=""alt="No data" />
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                    </div>
                                    <div class="col-5 p-1">
                                        <div class="card text-center align-middle">
                                            <div class="
                                                card-body
                                                align-items-center
                                                border
                                                rounded p-1">
                                                <span class="fs-6">{{pr.price.regular}}$</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                        <div class="border-start border-end border-top text-center">
                        {% if pr.available %}
                        <span class="fs-6">{{pr.name}}</span>
                        {% else %}
                        <span class="fs-6 text-muted">{{pr.name}}</span>
                        {% endif %}
                        </div>
                        <div class="card-footer border p-0">
                        <div class="d-flex flex-row">
                            <div class="
                                border-end
                                d-flex
                                justify-content-center
                                ps-2
                                pe-2
                                align-items-center
                            ">
                            {% if pr.available %}
                                <span class="fs-5">10</span>
                            {% else %}
                                <span class="fs-5 text-muted">10</span>
                            {% endif %}
                            </div>
                            {% if pr.available %}
                                <div class="d-flex flex-column align-items-center border-end">
                                    <a href="#">
                                        <svg class="border-bottom" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px"
                                            fill="#000000">
                                            <path d="M0 0h24v24H0V0z" fill="none" />
                                            <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" />
                                        </svg>
                                    </a>
                                    <a href="#">
                                        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px"
                                        fill="#000000">
                                            <path d="M0 0h24v24H0V0z" fill="none" />
                                            <path d="M19 13H5v-2h14v2z" />
                                        </svg>
                                    </a>
                                </div>
                                <a href="#" class="d-flex flex-fill justify-content-center align-items-center pt-2 pb-2 basket-button">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="25px" width="25px"  viewBox="0 0 24 24" 
                                    fill="#000000">
                                        <path d="M0 0h24v24H0V0z" fill="none" />
                                        <path
                                        d="M15.55 13c.75 0 1.41-.41 1.75-1.03l3.58-6.49c.37-.66-.11-1.48-.87-1.48H5.21l-.94-2H1v2h2l3.6 7.59-1.35 2.44C4.52 15.37 5.48 17 7 17h12v-2H7l1.1-2h7.45zM6.16 6h12.15l-2.76 5H8.53L6.16 6zM7 18c-1.1 0-1.99.9-1.99 2S5.9 22 7 22s2-.9 2-2-.9-2-2-2zm10 0c-1.1 0-1.99.9-1.99 2s.89 2 1.99 2 2-.9 2-2-.9-2-2-2z" />
                                    </svg>
                                </a>
                            {% else %}
                                <div class="d-flex flex-column align-items-center border-end">
                                    <svg class="border-bottom" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px"
                                        fill="#6c757d">
                                        <path d="M0 0h24v24H0V0z" fill="none" />
                                        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z" />
                                    </svg>
                                    <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px"
                                    fill="#6c757d">
                                        <path d="M0 0h24v24H0V0z" fill="none" />
                                        <path d="M19 13H5v-2h14v2z" />
                                    </svg>
                                </div>
                                <div class="d-flex flex-fill justify-content-center align-items-center pt-2 pb-2">
                                    <svg xmlns="http://www.w3.org/2000/svg" height="25px" width="25px"  viewBox="0 0 24 24" 
                                    fill="#6c757d">
                                        <path d="M0 0h24v24H0V0z" fill="none" />
                                        <path
                                        d="M15.55 13c.75 0 1.41-.41 1.75-1.03l3.58-6.49c.37-.66-.11-1.48-.87-1.48H5.21l-.94-2H1v2h2l3.6 7.59-1.35 2.44C4.52 15.37 5.48 17 7 17h12v-2H7l1.1-2h7.45zM6.16 6h12.15l-2.76 5H8.53L6.16 6zM7 18c-1.1 0-1.99.9-1.99 2S5.9 22 7 22s2-.9 2-2-.9-2-2-2zm10 0c-1.1 0-1.99.9-1.99 2s.89 2 1.99 2 2-.9 2-2-.9-2-2-2z" />
                                    </svg>
                                </div>
                            {% endif %}
                        </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% if products.has_other_pages %}
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    {% if products.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
                        </li>
                    {% endif %}
                    {% for i in products.paginator.page_range %}
                        {% if products.number == i %}
                            <li class="page-item active"><a class="page-link" href="?page={{ i }}">{{i}}</a></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{i}}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if products.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ products.next_page_number }}">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/offert/subcategory.html
{% extends "base.html" %}
{% load static %}
{% load custom_template_tags %}
{% block title %}{{title}}{% endblock %}
{% block stylesheet %}{% static "offert/css/offert_subcategory.css" %}{% endblock %}
{% block content %}
<div class="container pt-5">
    <div class="d-flex flex-row align-items-center">
    {% for an in ancestors %}
    {% if an == ancestors|last %}
        <a href="{% url 'offert:subcategory' an.slug %}" class="text-decoration-none navigator-text fw500 subcategory-nav">{{an.name}}</a>
    {% else %}
        <a href="{% url 'offert:subcategory' an.slug %}" class="text-decoration-none text-dark navigator-text fw500">{{an.name}}</a>
    {% endif %}
    {% if an != ancestors|last %}
    <svg xmlns="http://www.w3.org/2000/svg" class="ms-2 me-2" width="35" height="35" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
    </svg>
    {% endif %}
    {% endfor %}
    </div>
    <hr class="ms-0 me-0 mt-3 mb-3">
    <div>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
    <div class="row">
        {% for cat in category %}
        <div class="col-6 col-sm-6 col-md-4 col-lg-3 col-xl-3 col-xxl-2">
            {% if descendent_count|put_variable:cat != 0 %}
            <a href="{% url 'offert:subcategory' cat.slug %}" class="text-decoration-none">
            {% else %}
            <a href="{% url 'offert:products' cat.slug %}" class="text-decoration-none">
            {% endif %}
                <div class="card sub-category-card subcategory m-2">
                    <img src="{{cat.photo.url}}" alt="">
                    <div class="card-body">
                        <h6 class="card-text text-center link-dark">{{cat.name}}</h6>
                        {{descendent_count|put_variable:cat}}
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
{% endblock content %}